# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_get_cl_means <- function(mat, clAll) {
    .Call('_scrattch_bigcat_rcpp_get_cl_means', PACKAGE = 'scrattch.bigcat', mat, clAll)
}

rcpp_get_cl_means_RcppParallel <- function(mat, clAll) {
    .Call('_scrattch_bigcat_rcpp_get_cl_means_RcppParallel', PACKAGE = 'scrattch.bigcat', mat, clAll)
}

rcpp_get_cl_present <- function(mat, clAll, lowth) {
    .Call('_scrattch_bigcat_rcpp_get_cl_present', PACKAGE = 'scrattch.bigcat', mat, clAll, lowth)
}

rcpp_get_cl_present_RcppParallel <- function(mat, clAll, lowth) {
    .Call('_scrattch_bigcat_rcpp_get_cl_present_RcppParallel', PACKAGE = 'scrattch.bigcat', mat, clAll, lowth)
}

rcpp_get_cl_sqr_means <- function(mat, clAll) {
    .Call('_scrattch_bigcat_rcpp_get_cl_sqr_means', PACKAGE = 'scrattch.bigcat', mat, clAll)
}

rcpp_get_cl_sqr_means_RcppParallel <- function(mat, clAll) {
    .Call('_scrattch_bigcat_rcpp_get_cl_sqr_means_RcppParallel', PACKAGE = 'scrattch.bigcat', mat, clAll)
}

rcpp_get_cl_medians <- function(mat, clAll) {
    .Call('_scrattch_bigcat_rcpp_get_cl_medians', PACKAGE = 'scrattch.bigcat', mat, clAll)
}

rcpp_get_cl_medians_RcppParallel <- function(mat, clAll) {
    .Call('_scrattch_bigcat_rcpp_get_cl_medians_RcppParallel', PACKAGE = 'scrattch.bigcat', mat, clAll)
}

rcpp_get_cl_sums <- function(mat, clAll) {
    .Call('_scrattch_bigcat_rcpp_get_cl_sums', PACKAGE = 'scrattch.bigcat', mat, clAll)
}

rcpp_get_cl_sums_RcppParallel <- function(mat, clAll) {
    .Call('_scrattch_bigcat_rcpp_get_cl_sums_RcppParallel', PACKAGE = 'scrattch.bigcat', mat, clAll)
}

rcpp_get_cl_sqr_sums <- function(mat, clAll) {
    .Call('_scrattch_bigcat_rcpp_get_cl_sqr_sums', PACKAGE = 'scrattch.bigcat', mat, clAll)
}

rcpp_get_cl_sqr_sums_RcppParallel <- function(mat, clAll) {
    .Call('_scrattch_bigcat_rcpp_get_cl_sqr_sums_RcppParallel', PACKAGE = 'scrattch.bigcat', mat, clAll)
}

rcpp_get_cl_means_dense <- function(mat, clAll) {
    .Call('_scrattch_bigcat_rcpp_get_cl_means_dense', PACKAGE = 'scrattch.bigcat', mat, clAll)
}

rcpp_get_cl_means_RcppParallel_dense <- function(mat, clAll) {
    .Call('_scrattch_bigcat_rcpp_get_cl_means_RcppParallel_dense', PACKAGE = 'scrattch.bigcat', mat, clAll)
}

rcpp_get_cl_present_dense <- function(mat, clAll, lowth) {
    .Call('_scrattch_bigcat_rcpp_get_cl_present_dense', PACKAGE = 'scrattch.bigcat', mat, clAll, lowth)
}

rcpp_get_cl_present_RcppParallel_dense <- function(mat, clAll, lowth) {
    .Call('_scrattch_bigcat_rcpp_get_cl_present_RcppParallel_dense', PACKAGE = 'scrattch.bigcat', mat, clAll, lowth)
}

rcpp_get_cl_sqr_means_dense <- function(mat, clAll) {
    .Call('_scrattch_bigcat_rcpp_get_cl_sqr_means_dense', PACKAGE = 'scrattch.bigcat', mat, clAll)
}

rcpp_get_cl_sqr_means_RcppParallel_dense <- function(mat, clAll) {
    .Call('_scrattch_bigcat_rcpp_get_cl_sqr_means_RcppParallel_dense', PACKAGE = 'scrattch.bigcat', mat, clAll)
}

rcpp_get_cl_medians_dense <- function(mat, clAll) {
    .Call('_scrattch_bigcat_rcpp_get_cl_medians_dense', PACKAGE = 'scrattch.bigcat', mat, clAll)
}

rcpp_get_cl_medians_RcppParallel_dense <- function(mat, clAll) {
    .Call('_scrattch_bigcat_rcpp_get_cl_medians_RcppParallel_dense', PACKAGE = 'scrattch.bigcat', mat, clAll)
}

rcpp_get_cl_sums_dense <- function(mat, clAll) {
    .Call('_scrattch_bigcat_rcpp_get_cl_sums_dense', PACKAGE = 'scrattch.bigcat', mat, clAll)
}

rcpp_get_cl_sums_RcppParallel_dense <- function(mat, clAll) {
    .Call('_scrattch_bigcat_rcpp_get_cl_sums_RcppParallel_dense', PACKAGE = 'scrattch.bigcat', mat, clAll)
}

rcpp_get_cl_sqr_sums_dense <- function(mat, clAll) {
    .Call('_scrattch_bigcat_rcpp_get_cl_sqr_sums_dense', PACKAGE = 'scrattch.bigcat', mat, clAll)
}

rcpp_get_cl_sqr_sums_RcppParallel_dense <- function(mat, clAll) {
    .Call('_scrattch_bigcat_rcpp_get_cl_sqr_sums_RcppParallel_dense', PACKAGE = 'scrattch.bigcat', mat, clAll)
}

rcpp_get_cl_means_transpose <- function(mat, clAll) {
    .Call('_scrattch_bigcat_rcpp_get_cl_means_transpose', PACKAGE = 'scrattch.bigcat', mat, clAll)
}

rcpp_get_cl_means_RcppParallel_transpose <- function(mat, clAll) {
    .Call('_scrattch_bigcat_rcpp_get_cl_means_RcppParallel_transpose', PACKAGE = 'scrattch.bigcat', mat, clAll)
}

rcpp_get_cl_present_transpose <- function(mat, clAll, lowth) {
    .Call('_scrattch_bigcat_rcpp_get_cl_present_transpose', PACKAGE = 'scrattch.bigcat', mat, clAll, lowth)
}

rcpp_get_cl_present_RcppParallel_transpose <- function(mat, clAll, lowth) {
    .Call('_scrattch_bigcat_rcpp_get_cl_present_RcppParallel_transpose', PACKAGE = 'scrattch.bigcat', mat, clAll, lowth)
}

rcpp_get_cl_sqr_means_transpose <- function(mat, clAll) {
    .Call('_scrattch_bigcat_rcpp_get_cl_sqr_means_transpose', PACKAGE = 'scrattch.bigcat', mat, clAll)
}

rcpp_get_cl_sqr_means_RcppParallel_transpose <- function(mat, clAll) {
    .Call('_scrattch_bigcat_rcpp_get_cl_sqr_means_RcppParallel_transpose', PACKAGE = 'scrattch.bigcat', mat, clAll)
}

rcpp_get_cl_medians_transpose <- function(mat, clAll) {
    .Call('_scrattch_bigcat_rcpp_get_cl_medians_transpose', PACKAGE = 'scrattch.bigcat', mat, clAll)
}

rcpp_get_cl_medians_RcppParallel_transpose <- function(mat, clAll) {
    .Call('_scrattch_bigcat_rcpp_get_cl_medians_RcppParallel_transpose', PACKAGE = 'scrattch.bigcat', mat, clAll)
}

rcpp_get_cl_sums_transpose <- function(mat, clAll) {
    .Call('_scrattch_bigcat_rcpp_get_cl_sums_transpose', PACKAGE = 'scrattch.bigcat', mat, clAll)
}

rcpp_get_cl_sums_RcppParallel_transpose <- function(mat, clAll) {
    .Call('_scrattch_bigcat_rcpp_get_cl_sums_RcppParallel_transpose', PACKAGE = 'scrattch.bigcat', mat, clAll)
}

rcpp_get_cl_sqr_sums_transpose <- function(mat, clAll) {
    .Call('_scrattch_bigcat_rcpp_get_cl_sqr_sums_transpose', PACKAGE = 'scrattch.bigcat', mat, clAll)
}

rcpp_get_cl_sqr_sums_RcppParallel_transpose <- function(mat, clAll) {
    .Call('_scrattch_bigcat_rcpp_get_cl_sqr_sums_RcppParallel_transpose', PACKAGE = 'scrattch.bigcat', mat, clAll)
}

rcpp_get_cl_means_transpose_dense <- function(mat, clAll) {
    .Call('_scrattch_bigcat_rcpp_get_cl_means_transpose_dense', PACKAGE = 'scrattch.bigcat', mat, clAll)
}

rcpp_get_cl_means_RcppParallel_transpose_dense <- function(mat, clAll) {
    .Call('_scrattch_bigcat_rcpp_get_cl_means_RcppParallel_transpose_dense', PACKAGE = 'scrattch.bigcat', mat, clAll)
}

rcpp_get_cl_present_transpose_dense <- function(mat, clAll, lowth) {
    .Call('_scrattch_bigcat_rcpp_get_cl_present_transpose_dense', PACKAGE = 'scrattch.bigcat', mat, clAll, lowth)
}

rcpp_get_cl_present_RcppParallel_transpose_dense <- function(mat, clAll, lowth) {
    .Call('_scrattch_bigcat_rcpp_get_cl_present_RcppParallel_transpose_dense', PACKAGE = 'scrattch.bigcat', mat, clAll, lowth)
}

rcpp_get_cl_sqr_means_transpose_dense <- function(mat, clAll) {
    .Call('_scrattch_bigcat_rcpp_get_cl_sqr_means_transpose_dense', PACKAGE = 'scrattch.bigcat', mat, clAll)
}

rcpp_get_cl_sqr_means_RcppParallel_transpose_dense <- function(mat, clAll) {
    .Call('_scrattch_bigcat_rcpp_get_cl_sqr_means_RcppParallel_transpose_dense', PACKAGE = 'scrattch.bigcat', mat, clAll)
}

rcpp_get_cl_medians_transpose_dense <- function(mat, clAll) {
    .Call('_scrattch_bigcat_rcpp_get_cl_medians_transpose_dense', PACKAGE = 'scrattch.bigcat', mat, clAll)
}

rcpp_get_cl_medians_RcppParallel_transpose_dense <- function(mat, clAll) {
    .Call('_scrattch_bigcat_rcpp_get_cl_medians_RcppParallel_transpose_dense', PACKAGE = 'scrattch.bigcat', mat, clAll)
}

rcpp_get_cl_sums_transpose_dense <- function(mat, clAll) {
    .Call('_scrattch_bigcat_rcpp_get_cl_sums_transpose_dense', PACKAGE = 'scrattch.bigcat', mat, clAll)
}

rcpp_get_cl_sums_RcppParallel_transpose_dense <- function(mat, clAll) {
    .Call('_scrattch_bigcat_rcpp_get_cl_sums_RcppParallel_transpose_dense', PACKAGE = 'scrattch.bigcat', mat, clAll)
}

rcpp_get_cl_sqr_sums_transpose_dense <- function(mat, clAll) {
    .Call('_scrattch_bigcat_rcpp_get_cl_sqr_sums_transpose_dense', PACKAGE = 'scrattch.bigcat', mat, clAll)
}

rcpp_get_cl_sqr_sums_RcppParallel_transpose_dense <- function(mat, clAll) {
    .Call('_scrattch_bigcat_rcpp_get_cl_sqr_sums_RcppParallel_transpose_dense', PACKAGE = 'scrattch.bigcat', mat, clAll)
}

RowMergeMatrices <- function(mat1, mat2, mat1_rownames, mat2_rownames, all_rownames) {
    .Call('_scrattch_bigcat_RowMergeMatrices', PACKAGE = 'scrattch.bigcat', mat1, mat2, mat1_rownames, mat2_rownames, all_rownames)
}

RowMergeMatricesList <- function(mat_list, mat_rownames, all_rownames) {
    .Call('_scrattch_bigcat_RowMergeMatricesList', PACKAGE = 'scrattch.bigcat', mat_list, mat_rownames, all_rownames)
}

LogNorm <- function(data, scale_factor, display_progress = TRUE) {
    .Call('_scrattch_bigcat_LogNorm', PACKAGE = 'scrattch.bigcat', data, scale_factor, display_progress)
}

Standardize <- function(mat, display_progress = TRUE) {
    .Call('_scrattch_bigcat_Standardize', PACKAGE = 'scrattch.bigcat', mat, display_progress)
}

FastSparseRowScale <- function(mat, scale = TRUE, center = TRUE, scale_max = 10, display_progress = TRUE) {
    .Call('_scrattch_bigcat_FastSparseRowScale', PACKAGE = 'scrattch.bigcat', mat, scale, center, scale_max, display_progress)
}

FastSparseRowScaleWithKnownStats <- function(mat, mu, sigma, scale = TRUE, center = TRUE, scale_max = 10, display_progress = TRUE) {
    .Call('_scrattch_bigcat_FastSparseRowScaleWithKnownStats', PACKAGE = 'scrattch.bigcat', mat, mu, sigma, scale, center, scale_max, display_progress)
}

FastCov <- function(mat, center = TRUE) {
    .Call('_scrattch_bigcat_FastCov', PACKAGE = 'scrattch.bigcat', mat, center)
}

FastCovMats <- function(mat1, mat2, center = TRUE) {
    .Call('_scrattch_bigcat_FastCovMats', PACKAGE = 'scrattch.bigcat', mat1, mat2, center)
}

FastRBind <- function(mat1, mat2) {
    .Call('_scrattch_bigcat_FastRBind', PACKAGE = 'scrattch.bigcat', mat1, mat2)
}

SparseRowMean <- function(mat, display_progress) {
    .Call('_scrattch_bigcat_SparseRowMean', PACKAGE = 'scrattch.bigcat', mat, display_progress)
}

SparseRowVar2 <- function(mat, mu, display_progress) {
    .Call('_scrattch_bigcat_SparseRowVar2', PACKAGE = 'scrattch.bigcat', mat, mu, display_progress)
}

SparseRowVarStd <- function(mat, mu, sd, vmax, display_progress) {
    .Call('_scrattch_bigcat_SparseRowVarStd', PACKAGE = 'scrattch.bigcat', mat, mu, sd, vmax, display_progress)
}

FastLogVMR <- function(mat, display_progress) {
    .Call('_scrattch_bigcat_FastLogVMR', PACKAGE = 'scrattch.bigcat', mat, display_progress)
}

RowVar <- function(x) {
    .Call('_scrattch_bigcat_RowVar', PACKAGE = 'scrattch.bigcat', x)
}

SparseRowVar <- function(mat, display_progress) {
    .Call('_scrattch_bigcat_SparseRowVar', PACKAGE = 'scrattch.bigcat', mat, display_progress)
}

ReplaceColsC <- function(mat, col_idx, replacement) {
    .Call('_scrattch_bigcat_ReplaceColsC', PACKAGE = 'scrattch.bigcat', mat, col_idx, replacement)
}

GraphToNeighborHelper <- function(mat) {
    .Call('_scrattch_bigcat_GraphToNeighborHelper', PACKAGE = 'scrattch.bigcat', mat)
}

ImputeKnn <- function(knn_idx, ref_idx, cell_idx, gene_idx, dat, impute_dat, w_mat_, transpose_input, transpose_output) {
    invisible(.Call('_scrattch_bigcat_ImputeKnn', PACKAGE = 'scrattch.bigcat', knn_idx, ref_idx, cell_idx, gene_idx, dat, impute_dat, w_mat_, transpose_input, transpose_output))
}

ComputeSNN <- function(nn_ranked, prune) {
    .Call('_scrattch_bigcat_ComputeSNN', PACKAGE = 'scrattch.bigcat', nn_ranked, prune)
}

WriteEdgeFile <- function(snn, filename, display_progress) {
    invisible(.Call('_scrattch_bigcat_WriteEdgeFile', PACKAGE = 'scrattch.bigcat', snn, filename, display_progress))
}

DirectSNNToFile <- function(nn_ranked, prune, display_progress, filename) {
    .Call('_scrattch_bigcat_DirectSNNToFile', PACKAGE = 'scrattch.bigcat', nn_ranked, prune, display_progress, filename)
}

